### ISSUE TITLE
[PE-D][Tester D] viewp after listm

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W08-4/tp#135]
viewp claims to display the specified person, but after listm, there is no people in the displayed list. But viewp 1 stills display some person

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ong-wei-hong/ped#6

**Comment by LinWanLeii** [comment]
This one doesnt make sense, when you viewp its selecting from the person list doesnt matter what is being shown on the displayed list.

Can ignore
