### ISSUE TITLE
[PE-D][Tester C] Minor Issue with Medicine Short Form

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2103T-W08-4/tp#151]
Short form check allows the short form to be longer than the name of the medicine. I agree this is trivial and I labelled severity as verylow. Just a finding duing testing.

![image.png](https://raw.githubusercontent.com/mamayuan/ped/main/files/d61c6509-2af1-47ca-92a2-bc4053de8660.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: mamayuan/ped#5

**Comment by LinWanLeii** [comment]
Short form refers to how the user want to use it, doesn't necessarily mean that it must be shorter than the full form. Invalid bug
